version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
  db-testing-store:
  vendor-store:
  node_modules-store:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/var/www
      - vendor-store:/work/backend/vendor

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/var/www
      - node_modules-store:/work/backend/node_modules

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3307}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-jarvis}
      - MYSQL_USER=${DB_USER:-valleyin}
      - MYSQL_PASSWORD=${DB_PASS:-valleyin}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-valleyin}
    user: "1000:50"
    command: --innodb-use-native-aio=0

  db_testing:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - 3333:3306
    volumes:
      - db-testing-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=jarvis
      - MYSQL_USER=valleyin
      - MYSQL_PASSWORD=valleyin
      - MYSQL_ROOT_PASSWORD=valleyin
    user: "1000:50"
    command: --innodb-use-native-aio=0

  mail:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT:-8025}:8025
