<?php

namespace Tests\Unit\Requests;

use App\Http\Requests\RegisterRequest;
use App\Models\EmailVerification;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Tests\TestCase;

class RegisterRequestTest extends TestCase
{
    use RefreshDatabase;

    public function setUp() :void
    {
        parent::setUp();

        Mail::fake();
        Storage::fake('local');
        Log::spy();

        $this->email_verification = EmailVerification::create([
            'email' => 'test@test.com',
            'token' => 10000000000000,
            'status' => 0,
            'expiration_datetime' => Carbon::now()->addHours(1),
        ]);
    }
    /**
     * test for Register Request
     *
     * @param array
     * @param array
     * @param boolean
    * @dataProvider dataRegisterRequest
    */
    public function testRegisterRequest($url, array $keys, array $values, bool $expect)
    {
        $request = Request::create($url, 'POST');
        $dataList = array_combine($keys, $values);


        $rules = (new RegisterRequest())->rules($request);

        $validator = Validator::make($dataList, $rules);

        $result = $validator->passes();

        $this->assertEquals($expect, $result);
    }

    public function dataRegisterRequest()
    {
        return [
            'OK by company' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                true,
            ],
            'OK by talent' => [
                'talent/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                true,
            ],
            'name.required' => [
                'company/register/10000000000000',
                [
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'password.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'password_confirmation.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'password.regex' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    't1',
                    't1',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'password.confirmed' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test2222',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'office_address.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'phone_number.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'phone_number.regex' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '11111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'certificate_files.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'certificate_files.array' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'certificate_files.Rules/CertificationFiles' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'certificate_files.file' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        str_repeat('a', 45),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'certificate_files.mimes' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.php', 100, 'application/x-httpd-php'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'bank_name.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'bank_branch_name.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'AAA AAA',
                ],
                false,
            ],
            'bank_account_number.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    'AAA AAA',
                ],
                false,
            ],
            'bank_account_number.integer' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat('a', 15),
                    'AAA AAA',
                ],
                false,
            ],
            'bank_account_number.regex' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    11,
                    'AAA AAA',
                ],
                false,
            ],
            'bank_account_holder.required' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                ],
                false,
            ],
            'bank_account_holder.regex' => [
                'company/register/10000000000000',
                [
                    'name',
                    'password',
                    'password_confirmation',
                    'office_address',
                    'phone_number',
                    'recognition_of_service',
                    'certificate_files',
                    'bank_name',
                    'bank_branch_name',
                    'bank_account_number',
                    'bank_account_holder',
                ],
                [
                    'test user',
                    'test1111',
                    'test1111',
                    str_repeat('a', 45),
                    '111-1111-1111',
                    str_repeat('a', 45),
                    array (
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                        UploadedFile::fake()->create('test.pdf', 100, 'application/pdf'),
                    ),
                    str_repeat('a', 45),
                    str_repeat('a', 45),
                    str_repeat(1, 15),
                    'aaaaa',
                ],
                false,
            ],
        ];
    }
}
