name: Deploy Staging

#run the job to server when pull request is closed
on:
  pull_request:
    types: [closed]
    branches:
      - staging


jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-18.04
    steps:
      - name: deploy (run container), with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST}}
          port: ${{ secrets.SSH_PORT}}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PATHPHRASE }}
          script: |
            ls .
            source ~/.bash_profile
            cd ${{ secrets.SERVER_STAGING_PROJECT_DIR}}
            ls .
            git pull origin staging
            cd backend
            php -v
            make app-staging-init
